---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by guala.
--- DateTime: 02/06/2022 22:20
---

ESX = nil

TriggerEvent("esx:getSharedObject", function(obj) ESX = obj end)

local isMenuOpen = false

local wipe_menu = RageUI.CreateMenu("WIPE", "Liste des joueurs")
local subMenu1 = RageUI.CreateSubMenu(wipe_menu, "WIPE", "Êtes vous sûr de vouloir le wipe")
wipe_menu.Closed = function()
    isMenuOpen = false
end

CreateThread(function()
    while true do
        ESX.TriggerServerCallback("nWipe:getPlayerList", function(result)
            nPlayer = result
        end)
        Wait(Config.refreshTime)
    end
end)

RegisterNetEvent("nWipe:checkIsAdminOk")
AddEventHandler("nWipe:checkIsAdminOk", function()
    for i = 1, #nPlayer do
        table.sort(nPlayer[i])
    end
    WipeMenu()
end)

local source = {}
local name = ""

function WipeMenu()
    if not isMenuOpen then
        isMenuOpen = true
        RageUI.Visible(wipe_menu, true)
        while isMenuOpen do
            RageUI.IsVisible(wipe_menu, function()
                RageUI.Separator("Joueur connecter : ~o~"..#nPlayer)
                RageUI.Line()
                for _, v in ipairs(nPlayer) do
                    RageUI.Button("[~r~"..v.source.."~s~] - "..tostring(v.name), nil, {RightLabel = "~o~Wipe~s~ →→"}, true, {
                        onSelected = function()
                            source = v.source
                            name = v.name
                        end
                    }, subMenu1)
                end
            end)
            RageUI.IsVisible(subMenu1, function()
                RageUI.Button("Non", nil, {RightLabel = "→"}, true, {
                    onSelected = function()
                        RageUI.GoBack()
                    end
                })
                RageUI.Line()
                RageUI.Separator("~r~Après cette action vous ne pourrez")
                RageUI.Separator("~r~pas revenir en arrière")
                RageUI.Button("Oui", nil, {RightBadge = RageUI.BadgeStyle.Alert}, true, {
                    onSelected = function()
                        TriggerServerEvent("nWipe:wipePlayer", source)
                        RageUI.GoBack()
                    end
                })
            end)
            Wait(1)
        end
    end
end

RegisterCommand(Config.commande, function()
    TriggerServerEvent("nWipe:checkPerm")
end)
