---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by NRC.
--- DateTime: 02/06/2022 22:20
---

Config = {}

Config.commande = "wipe" -- Commande pour ouvrir le menu

Config.refreshTime = 4000 -- Refresh du menu tous les 4s

function WipeTable(targetId) -- Table à vider pour le wipe
    MySQL.Sync.execute("DELETE FROM users WHERE identifier='" .. targetId .. "'")
    MySQL.Sync.execute("DELETE FROM billing WHERE identifier='" .. targetId .. "'")
    MySQL.Sync.execute("DELETE FROM open_car WHERE identifier='" .. targetId .. "'")
    MySQL.Sync.execute("DELETE FROM owned_vehicles WHERE owner='" .. targetId .. "'")
    MySQL.Sync.execute("DELETE FROM impounded_vehicles WHERE owner='" .. targetId .. "'")
    MySQL.Sync.execute("DELETE FROM addon_inventory_items WHERE owner='" .. targetId .. "'")
    MySQL.Sync.execute("DELETE FROM addon_account_data WHERE owner='" .. targetId .. "'")
    MySQL.Sync.execute("DELETE FROM owned_properties WHERE owner='" .. targetId .. "'")
    MySQL.Sync.execute("DELETE FROM owned_vehicles WHERE owner='" .. targetId .. "'")
    MySQL.Sync.execute("DELETE FROM users_licenses WHERE owner='" .. targetId .. "'")
    MySQL.Sync.execute("DELETE FROM datastore_data WHERE owner='" .. targetId .. "'")
end

Config.WipeLog = "" -- WebHook discord