---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by guala.
--- DateTime: 02/06/2022 22:20
---
ESX = nil 

TriggerEvent("esx:getSharedObject", function(obj) ESX = obj end)

ESX.RegisterServerCallback("nWipe:getPlayerList", function(source, cb)
    local Players = {}
    local xPlayers = ESX.GetPlayers();

    for i = 1, #xPlayers, 1 do
        local xPlayer = ESX.GetPlayerFromId(xPlayers[i]);

        table.insert(Players, {
            group = xPlayer.getGroup(),
            source = xPlayer.source,
            name = xPlayer.getName(),
        })
    end
    cb(Players)
end)

RegisterNetEvent("nWipe:checkPerm")
AddEventHandler("nWipe:checkPerm", function()
    local _src = source
    local xPlayer = ESX.GetPlayerFromId(_src)

    if xPlayer.getGroup() ~= "user" then
        TriggerClientEvent("nWipe:checkIsAdminOk", _src)
    else
        return TriggerClientEvent("esx:showNotification", _src, "Vous n'avez pas les permissions de faire cela !!")
    end
end)

RegisterNetEvent("nWipe:wipePlayer")
AddEventHandler("nWipe:wipePlayer", function(target)
    local _src = source
    local xPlayer = ESX.GetPlayerFromId(_src)
    local xTarget = ESX.GetPlayerFromId(target)

    if xTarget == nil then
        return TriggerClientEvent("esx:showNotification", _src, "Le joueur n'est plus connecter")
    end

    if xPlayer.getGroup() == "user" then
        DropPlayer(source, "Vous n'avez pas les permission de faire cela")
        return
    end

    WipeTable(xTarget.identifier)
    DropPlayer(target, "[nWipe] - Vous avez été wipe...")
    TriggerClientEvent("esx:showNotification", _src, "~g~Wipe effectuer")

    local w = {{ ["author"] = { ["name"] = "🪐 nWipe", ["icon_url"] = "https://cdn.discordapp.com/attachments/886646425243517028/946471181744222279/logo_nrcShop2.png" }, ["color"] = "10038562", ["title"] = Title, ["description"] = "**Nouveau wipe :**\n\n**Staff :** ``"..xPlayer.getName().."``\n**Joueur :** ``"..xTarget.getName().."``", ["footer"] = { ["text"] = "🪐 "..os.date("%d/%m/%Y | %X"), ["icon_url"] = nil}, } }
    PerformHttpRequest(Config.WipeLog, function(err, text, headers) end, 'POST', json.encode({username = "nWipe", embeds = w, avatar_url = "https://cdn.discordapp.com/attachments/886646425243517028/946471181744222279/logo_nrcShop2.png"}), { ['Content-Type'] = 'application/json'})
end)
